language: php
sudo: false
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - travis_retry composer install --prefer-dist --no-interaction

script: phpunit

after_success:
  - travis_retry php vendor/bin/coveralls
